# -*- coding: utf-8 -*-
"""Penurunan Suhu Kopi

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K69CklMXmKyyrt73pyPKP46OZ6IOGMY2

##Arsandy Jati Pratama // 662023003

---

#penurunan_suhukopi
"""

# impor pustaka yang diperlukan
import numpy as np
import matplotlib.pyplot as plt

# Fungsi untuk menyelesaikan persamaan diferensial secara analitik
def suhu_kopi(t, T0, Ta, k):
    """
    Menyelesaikan T = Ta + e(-k * t) *(T0-Ta)

    Parameter:
      t   : array-like, titik waktu
      T0  : float, suhu kopi
      Ta  : float, suhu ruangan
      k   : float, konstanta laju pendinginan

    Mengembalikan:
      T   : array-like, suhu pada setiap titik waktu
    """
    return Ta + np.exp(-k * t) * (T0-Ta)
    #sepertinya ada kesalahan dalam rumus papan tulis kemarin ,
    #saya coba menggunakan rumus di papan tulis dan menyebabkan suhu awal yang saya tulis dan suhu awal pada grafik berbeda
    #dan ternyata ada sedikit kekeliruan dalam mencari konstanta nilai c

# Parameter contoh
T0 = 80  # Suhu awal kopi (derajat Celcius)
Ta = 25  # Suhu ruangan (derajat Celcius)
k = 0.1  # Konstanta laju pendinginan
t = np.linspace(0, 50, 200)  # # Titik waktu dari 0 hingga 50

# Menyelesaikan persamaan
T = suhu_kopi(t, T0, Ta, k)

# Plot hasilnya
plt.figure(figsize=(8, 6))
plt.plot(t, T, label=f'T0 = {T0}°C, Ta = {Ta}°C, k = {k}',color="magenta")
plt.title('Penurunan Suhu Kopi')
plt.xlabel('Waktu (menit)')
plt.ylabel('Suhu Kopi (°C)')
plt.grid()
plt.legend()
plt.show()