# -*- coding: utf-8 -*-
"""Pertumbuhan Logistik

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KnRa_S6vACPqX37gL7BJS39ALLxtNAtU

##Arsandy Jati Pratama // 662023003

#Pertumbuhan_Logistik
"""

#impor pustakaa yang diperlukan
import numpy as np
import matplotlib.pyplot as plt

# Fungsi untuk menyelesaikan persamaan diferensial secara analitikk
def distribusi_logistik(K, P0, r, t):
  """
  Menyelesaikan P(t) = K / (1 + ((K - P0) / P0) * e^(-r * t))

    Parameter:
      t   : array-like, waktu ( misalnya dalam bulan )
      P0  : float, jumlah karung beras yang didistribusikan pada bulan awal
      r   : float, laju pertumbuhan distribusi

    Mengembalikan:
      P   : array-like, Jumlah karung beras yang telah didistribusikan pada waktu t
  """
  return K / (1 + ((K - P0) / P0) * np.exp(-r * t))

# Parameter yang diberikann
K = 10000  # kapasitas maksimum sistem logistik (misalnya kapasitas gudang)
r = 0.5  # laju pertumbuhan distribusi per bulan
P0 = 1000  # jumlah karung beras yang didistribusikan pada bulan pertama

# Waktu (bulan)
t_values = np.linspace(0, 12, 100)  # Menampilkan grafik selama 12 bulan dengan 100 titik dataa
P_values = distribusi_logistik(K, P0, r, t_values)

# Menghitung jumlah karung beras setelah bulan ke-5
t_5 = 5 # bulan ke 5
P_5 = distribusi_logistik(K, P0, r, t_5)

# Menampilkan hasil jumlah karung beras setelah bulan ke-5
print(f"Jumlah Karung Beras distribusi setelah bulan ke-{t_5} adalah {P_5:.2f} karung.") # di ambil 2 digit belakang koma sajaa

# Membuat grafik
plt.figure(figsize=(8, 6))
plt.plot(t_values, P_values, label='Distribusi Barang', color='blue', linewidth=2) #linewidth untuk ketebalan garis
plt.axvline(x=t_5, color='red', linestyle='--', label=f"Bulan ke-{t_5}") #menambahkan garis vertikal di bulan 5
plt.scatter(t_5, P_5, color='red', zorder=5)  # menambahkan itik untuk bulan ke-5 dan zorder untuk urutan tumpukan elemen


# Menambahkan label dan judul
plt.title("Perkembangan Distribusi karung beras dengan Model Logistik", fontsize=13) # judul dan fontsize untuk ukuran font
plt.xlabel("Waktu (Bulan)", fontsize=11) # nama x label dan fontsize untuk ukuran font
plt.ylabel("Jumlah Karung Beras yang Didistribusikan", fontsize=11) # nama y label dan fontsize untuk ukuran font
plt.legend()

# Menampilkan grid
plt.grid()

# Menampilkan grafik
plt.show()