# -*- coding: utf-8 -*-
"""Nilai Eigen & Vektor Eigen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zrVlyWhr8FFVryqzaMqVsmYXGWE3YW1y

#Matrik 2x2
"""

import numpy as san

A = san.array([[4,1],[2,3]])

nilaieigen, vektoreigen = san.linalg.eig(A)

print("nilaieigen:")
print(nilaieigen)
print("\nvektoreigen:")
print(vektoreigen)

"""#matrik 3x3"""

A = san.array([[1,1,1],[2,2,2],[3,3,3]])

nilaieigen, vektoreigen = san.linalg.eig(A)

print("nilaieigen:")
print(nilaieigen)
print("\nvektoreigen:")
print(vektoreigen)