# -*- coding: utf-8 -*-
"""Simulasi Penyebaran HIV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jFH8qx8iMllKnUu-JUrfT8tQsSw0Cqvo

# ARSANDY JATI PRATAMA / 662023003

# SIMULASI PENYEBARAN HIV SELAMA 100 HARI
"""

import numpy as np
import matplotlib.pyplot as plt

# Parameter model
N = 1000        # Tingkat Populasi
beta = 0.002    # tingkat Penularan
gamma = 0.1     # Laju perkembangan ke AIDS
mu = 0.01       # Tingkat kematian alami
delta = 0.2     # tingkat kematian akibat AIDS

# Kondisi awal
H0 = 900      # orang rentang
I0 = 80       # orang kemungkinan terinfeksi
V0 = 20       # penderita hiv

# Waktu Simulasi
T = 100     # Durasi dalam sehari
dt = 1      # Langkah Waktu

# Vektor waktu
time = np.arange(0, T + dt, dt)

# Array untuk menyimpan hasil simulasi
H = np.zeros(len(time))
I = np.zeros(len(time))
V = np.zeros(len(time))

# Inisialisa Kondisi Awal
H[0] = H0
I[0] = I0
V[0] = V0

# Simulasi dengan metode euler
for t in range(1,len(time)):
    dH = mu * N - beta * H [t-1] * I[t-1] - mu*H[t-1]
    dI = beta * H[t-1] * I[t-1] - (gamma + mu) * I[t-1]
    dV = gamma * I [t-1] - (delta+mu) * V [t-1]

    # Update Populasi
    H[t] = H[t-1] + dH * dt
    I[t] = I[t-1] + dI * dt
    V[t] = V[t-1] + dV * dt

# Plot hasil simulasi
plt.figure(figsize=(10,6))
plt.plot(time, H, label='Rentan (H)',color = 'green',linewidth = 2)
plt.plot(time, I, label='Terinfeksi HIV (I)',linewidth = 2)
plt.plot(time, V, label='AIDS (V)',color = 'magenta',linewidth = 2)

plt.title('Simulasi Penyebaran HIV selama 100 hari')
plt.xlabel('Hari')
plt.ylabel('Jumlah Populasi')
plt.legend()
plt.grid(True)
plt.show()